name: figma_challenge
description: "Aplicación basada en diseño de Figma"
publish_to: 'none'
version: 1.1.0+5

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.4
  intl: ^0.20.2
  flutter_svg: ^2.2.1
  animate_do: ^4.2.0
  sqflite: ^2.4.2
  table_calendar: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/plane.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/new_flight/
    - assets/images/airlines/
    - assets/images/airports/
    - assets/images/wallpaper/
    - assets/icons/
    - assets/icons/tabbar/
    - lib/data/

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat.ttf

    - family: Montserrat-ExtraBold
      fonts:
        - asset: fonts/Montserrat-ExtraBold.ttf

    - family: Helvetica
      fonts:
        - asset: fonts/Helvetica.ttf

    - family: Helvetica-Bold
      fonts:
        - asset: fonts/Helvetica-Bold.ttf

    - family: Gigasans-Bold
      fonts:
        - asset: fonts/gigasans-bold.otf

    - family: Gigasans-ExtraBold
      fonts:
        - asset: fonts/gigasans_extrabold.otf

    - family: Rebelton-Bold
      fonts:
        - asset: fonts/rebelton-bold.ttf

    - family: SF-Pro
      fonts:
        - asset: fonts/sf_pro.otf
  # Para agregar assets a tu aplicación, descomenta y edita lo siguiente:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # Para agregar fuentes personalizadas, descomenta y edita lo siguiente:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700